export const testSudoku = {
  board: {
    R1: {
      C1: {
        name: "R1C1",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 8,
        notes: [],
      },
      C2: {
        name: "R1C2",
        isGiven: true,
        isFilled: true,
        value: 3,
        correctValue: 3,
        notes: [],
      },
      C3: {
        name: "R1C3",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 7,
        notes: [],
      },
      C4: {
        name: "R1C4",
        isGiven: true,
        isFilled: true,
        value: 2,
        correctValue: 2,
        notes: [],
      },
      C5: {
        name: "R1C5",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 1,
        notes: [],
      },
      C6: {
        name: "R1C6",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 9,
        notes: [],
      },
      C7: {
        name: "R1C7",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 4,
        notes: [],
      },
      C8: {
        name: "R1C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 5,
        notes: [],
      },
      C9: {
        name: "R1C9",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 6,
        notes: [],
      },
    },
    R2: {
      C1: {
        name: "R2C1",
        isGiven: true,
        isFilled: true,
        value: 2,
        correctValue: 2,
        notes: [],
      },
      C2: {
        name: "R2C2",
        isGiven: true,
        isFilled: true,
        value: 9,
        correctValue: 9,
        notes: [],
      },
      C3: {
        name: "R2C3",
        isGiven: true,
        isFilled: true,
        value: 6,
        correctValue: 6,
        notes: [],
      },
      C4: {
        name: "R2C4",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 4,
        notes: [],
      },
      C5: {
        name: "R2C5",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 8,
        notes: [],
      },
      C6: {
        name: "R2C6",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 5,
        notes: [],
      },
      C7: {
        name: "R2C7",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 3,
        notes: [],
      },
      C8: {
        name: "R2C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 2,
        notes: [],
      },
      C9: {
        name: "R2C9",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 7,
        notes: [],
      },
    },
    R3: {
      C1: {
        name: "R3C1",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 2,
        notes: [],
      },
      C2: {
        name: "R3C2",
        isGiven: true,
        isFilled: true,
        value: 4,
        correctValue: 4,
        notes: [],
      },
      C3: {
        name: "R3C3",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 5,
        notes: [],
      },
      C4: {
        name: "R3C4",
        isGiven: true,
        isFilled: true,
        value: 7,
        correctValue: 7,
        notes: [],
      },
      C5: {
        name: "R3C5",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 3,
        notes: [],
      },
      C6: {
        name: "R3C6",
        isGiven: true,
        isFilled: true,
        value: 6,
        correctValue: 6,
        notes: [],
      },
      C7: {
        name: "R3C7",
        isGiven: true,
        isFilled: true,
        value: 1,
        correctValue: 1,
        notes: [],
      },
      C8: {
        name: "R3C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 8,
        notes: [],
      },
      C9: {
        name: "R3C9",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 9,
        notes: [],
      },
    },
    R4: {
      C1: {
        name: "R4C1",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 4,
        notes: [],
      },
      C2: {
        name: "R4C2",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 6,
        notes: [],
      },
      C3: {
        name: "R4C3",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 3,
        notes: [],
      },
      C4: {
        name: "R4C4",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 5,
        notes: [],
      },
      C5: {
        name: "R4C5",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 7,
        notes: [],
      },
      C6: {
        name: "R4C6",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 2,
        notes: [],
      },
      C7: {
        name: "R4C7",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 8,
        notes: [],
      },
      C8: {
        name: "R4C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 9,
        notes: [],
      },
      C9: {
        name: "R4C9",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 1,
        notes: [],
      },
    },
    R5: {
      C1: {
        name: "R5C1",
        isGiven: true,
        isFilled: true,
        value: 5,
        correctValue: 5,
        notes: [],
      },
      C2: {
        name: "R5C2",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 2,
        notes: [],
      },
      C3: {
        name: "R5C3",
        isGiven: true,
        isFilled: true,
        value: 1,
        correctValue: 1,
        notes: [],
      },
      C4: {
        name: "R5C4",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 9,
        notes: [],
      },
      C5: {
        name: "R5C5",
        isGiven: true,
        isFilled: true,
        value: 6,
        correctValue: 6,
        notes: [],
      },
      C6: {
        name: "R5C6",
        isGiven: true,
        isFilled: true,
        value: 8,
        correctValue: 8,
        notes: [],
      },
      C7: {
        name: "R5C7",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 7,
        notes: [],
      },
      C8: {
        name: "R5C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 3,
        notes: [],
      },
      C9: {
        name: "R5C9",
        isGiven: true,
        isFilled: true,
        value: 4,
        correctValue: 4,
        notes: [],
      },
    },
    R6: {
      C1: {
        name: "R6C1",
        isGiven: true,
        isFilled: true,
        value: 7,
        correctValue: 7,
        notes: [],
      },
      C2: {
        name: "R6C2",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 8,
        notes: [],
      },
      C3: {
        name: "R6C3",
        isGiven: true,
        isFilled: true,
        value: 9,
        correctValue: 9,
        notes: [],
      },
      C4: {
        name: "R6C4",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 3,
        notes: [],
      },
      C5: {
        name: "R6C5",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 4,
        notes: [],
      },
      C6: {
        name: "R6C6",
        isGiven: true,
        isFilled: true,
        value: 1,
        correctValue: 1,
        notes: [],
      },
      C7: {
        name: "R6C7",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 2,
        notes: [],
      },
      C8: {
        name: "R6C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 6,
        notes: [],
      },
      C9: {
        name: "R6C9",
        isGiven: true,
        isFilled: true,
        value: 5,
        correctValue: 5,
        notes: [],
      },
    },
    R7: {
      C1: {
        name: "R7C1",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 3,
        notes: [],
      },
      C2: {
        name: "R7C2",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 5,
        notes: [],
      },
      C3: {
        name: "R7C3",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 8,
        notes: [],
      },
      C4: {
        name: "R7C4",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 1,
        notes: [],
      },
      C5: {
        name: "R7C5",
        isGiven: true,
        isFilled: true,
        value: 9,
        correctValue: 9,
        notes: [],
      },
      C6: {
        name: "R7C6",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 7,
        notes: [],
      },
      C7: {
        name: "R7C7",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 6,
        notes: [],
      },
      C8: {
        name: "R7C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 4,
        notes: [],
      },
      C9: {
        name: "R7C9",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 2,
        notes: [],
      },
    },
    R8: {
      C1: {
        name: "R8C1",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 9,
        notes: [],
      },
      C2: {
        name: "R8C2",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 7,
        notes: [],
      },
      C3: {
        name: "R8C3",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 4,
        notes: [],
      },
      C4: {
        name: "R8C4",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 6,
        notes: [],
      },
      C5: {
        name: "R8C5",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 2,
        notes: [],
      },
      C6: {
        name: "R8C6",
        isGiven: true,
        isFilled: true,
        value: 3,
        correctValue: 3,
        notes: [],
      },
      C7: {
        name: "R8C7",
        isGiven: true,
        isFilled: true,
        value: 5,
        correctValue: 5,
        notes: [],
      },
      C8: {
        name: "R8C8",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 1,
        notes: [],
      },
      C9: {
        name: "R8C9",
        isGiven: true,
        isFilled: true,
        value: 8,
        correctValue: 8,
        notes: [],
      },
    },
    R9: {
      C1: {
        name: "R9C1",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 6,
        notes: [],
      },
      C2: {
        name: "R9C2",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 1,
        notes: [],
      },
      C3: {
        name: "R9C3",
        isGiven: true,
        isFilled: true,
        value: 2,
        correctValue: 2,
        notes: [],
      },
      C4: {
        name: "R9C4",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 8,
        notes: [],
      },
      C5: {
        name: "R9C5",
        isGiven: true,
        isFilled: true,
        value: 5,
        correctValue: 5,
        notes: [],
      },
      C6: {
        name: "R9C6",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 4,
        notes: [],
      },
      C7: {
        name: "R9C7",
        isGiven: true,
        isFilled: true,
        value: 9,
        correctValue: 9,
        notes: [],
      },
      C8: {
        name: "R9C8",
        isGiven: true,
        isFilled: true,
        value: 7,
        correctValue: 7,
        notes: [],
      },
      C9: {
        name: "R9C9",
        isGiven: false,
        isFilled: false,
        value: 0,
        correctValue: 3,
        notes: [],
      },
    },
  },
};
